output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region"
  value       = var.region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.cluster_name
}

output "project_domain_name" {
  description = "domain name associated with this project"
  value       = local.project_domain_name
}

output "hosted_zone" {
  value       = aws_route53_zone.main.zone_id
  description = "id of the hosted zone for the project"
}

output "name_servers" {
  value       = aws_route53_zone.main.name_servers
  description = "name servers for the project"
}

output "iam_role_external_dns_arn" {
  value       = aws_iam_role.external_dns.arn
  description = "IAM role for external DNS"
}

output "iam_role_cert_manager_arn" {
  value       = aws_iam_role.cert_manager.arn
  description = "IAM role for cert-manager"
}

output "kms_key_arn" {
  value       = aws_kms_key.kms_key.arn
  description = "KMS key"
}

output "iam_role_kms_arn" {
  value       = aws_iam_role.kms.arn
  description = "IAM role for KMS"
}

output "efs_main" {
  value       = aws_efs_file_system.main.id
  description = "EFS ID"
}

output "iam_role_autoscaler_arn" {
  value       = aws_iam_role.autoscaler.arn
  description = "IAM role for autoscaler"
}

output "s3_airflow_bucket" {
  value       = aws_s3_bucket.airflow.bucket
  description = "S3 bucket where Airflow logs are placed"
}


output "iam_role_airflow_arn" {
  value       = aws_iam_role.airflow.arn
  description = "IAM role for Airflow"
}
